coronalabs/corona-docs

- markdown/api/event/mouse/index.markdown
- markdown/api/event/mouse/isAltDown.markdown
- markdown/api/event/mouse/isCommandDown.markdown
- markdown/api/event/mouse/isCtrlDown.markdown
- markdown/api/event/mouse/isShiftDown.markdown
- markdown/api/event/mouse/scrollX.markdown
- markdown/api/event/mouse/scrollY.markdown
- markdown/api/event/mouse/type.markdown
- markdown/api/event/touch/index.markdown
- markdown/api/event/touch/xDelta.markdown
- markdown/api/event/touch/yDelta.markdown
- markdown/guide/html5/plugins/index.markdown
Added several undocumented, yet functional mouse event properties with examples. There's also mouse event clickCount property, but it didn't seem to work so I didn't add it.
Also fixed a tabulation error in touch event examples and a typo in HTML5 plugin documentation.
Finally, just as a note, the two "VK Direct Games plugin" sample links in https://docs.coronalabs.com/guide/html5/plugins/index.html#plugin-example don't work. They require signing in to BitBucket, but after signing BitBucket tells that I don't have access to said files.
> Add undocumented mouse event properties and other minor fixes

- markdown/api/library/table/insert.markdown
Added simplified new examples to table.insert(). Using table.concat() to print out table elements looked confusing so I removed that and used comments to show table elements. New examples also cover all three use cases.
Added table.insert() usage details to 'Gotchas' like the function ignoring the position parameter when called with 2 parameters instead of 3. Also, moved the usage note about the length operator being faster to 'Gotchas'.
> Simplified table.insert examples and added usage details

- markdown/api/library/table/insert.markdown
- markdown/guide/physics/collisionDetection/index.markdown
- markdown/guide/physics/physicsSetup/index.markdown
Added a link to Physics Notes/Limitations at the end of working with display groups warning. There are a few tips at the notes that should be considered.
Moved working with display groups warning a bit higher to "Physics Setup" so developers would take that into account when starting to work with physics. It was under .setDrawMode() before. I thought that's more of a general physics advice than a certain function.
Added working with display groups warning to "Collision Handling". Thought that would be a good reminder and time saver at that point for developers who are struggling to make physics work.
> Changed physics - working with display groups warning

- README.md
- bin/build.lua
- markdown/native/hostedPlugin.markdown
- markdown/native/index.markdown
Changed core product and native product variables in build.lua so all references to that variable would be changed in the docs. There are still many places that doesn't use those variables so more work is needed.
There is a reference to Corona Marketplace in [native documentation](https://docs.coronalabs.com/native/index.html#plugin-development). I know there are alternatives but not sure if I should point them out at this point. Please let me know if you want this link changed.
In self-hosted plugins page, I was not sure if I should change it to Solar2D core product instead of native so I kept it that way. Also, in the same page [Running Plugins in the Simulator](https://docs.coronalabs.com/native/hostedPlugin.html#running-plugins-in-the-simulator)  only references macOS. If it works on …
> Rebranding references, updating self-hosted plugins

- resources/bodyPrefix.html
Changed icon redirection link to the documents homepage. Most of the time, this is the expected behavior.
> Changed redirection link

- bin/build.lua
- markdown/guide/start/installWin/index.markdown
Changed revision label wording. "Current Release" string which I added with the earlier request didn't make sense when I took a second look at it. This one is better.
Changed download link constant to REVISION_URL. This should make it work but if it won't, I'll make another request to fix it with a simple string.
Removed usage of constants for **bold** stylized items. It seems that when a text is stylized, build.lua constant is ignored.
@Shchvova the last pull request seems to have broken some stuff, sorry about that. This is a fix to make it work. I'd suggest merging it as soon as possible.
> Fixes for Windows install page

- markdown/guide/programming/intro/index.markdown
Latest commit was causing legal disclaimer to overlap the whole page. Hopefully, this one fixes the issue.
> Fix for legal disclaimer overlap

- markdown/guide/distribution/liveBuild/index.markdown
This is not a complete rebranding. This page must be revisited when all Solar-related applications like the Simulator, Live Server etc. are renamed. Removing all references to Corona can be confusing at this point.
Updated forum link to Solar2D.
> Changed branding, updated links

- markdown/api/library/composer/index.markdown
- markdown/api/library/easing/index.markdown
- markdown/api/library/timer/index.markdown
- markdown/api/library/timer/performWithDelay.markdown
- markdown/api/library/transition/index.markdown
- markdown/api/library/widget/index.markdown
Added references to the source codes of `composer.*`, `easing.*`, `timer.*`, `transition.*` and `widget.*` libraries.
Moved source code reference of `timer` to its index page.
> Added references to source code

- bin/build.lua
- markdown/guide/programming/01/index.markdown
- markdown/guide/start/installWin/index.markdown
Updated build version - `build.lua`
Fixed text editor package name for Atom autocomplete - `installWin`
Added link to Discord channel
Added information about SVG being supported through plugin
Updated links for forums and text editors
Removed feedback survey
Additional information: I changed the old marketplace link of Xcode Editor to GitHub repo since marketplace is no longer active. Hey @jcbnlsn ! If you are still interested in selling / maintaining the Xcode Editor, you may want to look for an alternative solution.
> Added links and new information, rebranding

- bin/build.lua
- markdown/guide/index.markdown
- markdown/guide/start/index.markdown
- markdown/guide/start/installMac/index.markdown
- markdown/guide/start/installWin/index.markdown
- markdown/guide/start/systemReqs/index.markdown
Removed branding for `System Requirements`
Removed `Product Activation` subsection and public / daily build references - macOS
Fixed `CURRENT_RELEASE` not displaying correctly
Updated JDK8 file name - both Windows and macOS
Updated download links for Solar2D, JDK8 and text editor packages - macOS
Added link to `Command Line Usage` subsection from menu on top - both Windows and macOS
Moved `Command Line Usage` subsection before `Getting Started` subsection - both Windows and macOS
> Updated Installing pages +a small fix

- markdown/guide/events/appNotification/index.markdown
Updated OneSignal link to GitHub repo - old one was broken
Updated forums link
Added link to Discord channel
Removed <nobr> for notification services' names
> Updated links, rebranding

- bin/build.lua
- markdown/404.markdown
- markdown/coronacards/index.markdown
- markdown/index.markdown
- resources/nav.markdown
Added constant for CoronaCards - `build.lua`
Removed link to http://coronacards.com/ and replaced it with GitHub Releases page - will add the FAQ page to docs
Added supported frameworks for CoronaCards
Added link to CoronaCards from the documentation index page
Added link to CoronaCards from the navigation bar
Fixed 404 message
CoronaCards seems to be well hidden, even though, it is still being used by developers and still included in the releases so I thought why don't we make it more visible :)
> Making CoronaCards visible

- markdown/coronacards/android/index.markdown
- markdown/coronacards/android/project.markdown
- markdown/coronacards/faq/index.markdown
- markdown/coronacards/index.markdown
- markdown/coronacards/ios/index.markdown
- markdown/guide/basics/index.markdown
- markdown/guide/programming/intro/index.markdown
Added FAQ page from CoronaCards.com. Edited it a little bit and used constants for Solar2D product references.
Updated installation links for iOS and Android. Haven't done the same for Windows Phone though :D
Android: Removed licensing reference though I'm not sure if it's still necessary but the link was not working. You may want to look into this before merging.
Small fixes:
Edited `Getting Started` guide to use `CORONA_CARDS_PRODUCT` variable
Removed branding on `Basics` page
> CoronaCards: Added FAQ, updated installation links

- markdown/guide/distribution/buildSettings/index.markdown
Moved Splash Screen Control plugin instructions to Project Build Settings to avoid confusion since it doesn't behave like a plugin and not purchased or activated anymore.
> Build settings: Added splash screen config, rebranding

- markdown/api/library/network/canDetectNetworkStatusChanges.markdown
- markdown/api/library/network/cancel.markdown
- markdown/api/library/network/download.markdown
- markdown/api/library/network/request.markdown
- markdown/api/library/network/setStatusListener.markdown
- markdown/api/library/network/upload.markdown
- markdown/tutorial/social/connectREST/index.markdown
Replaced branding with constants for "Connecting to REST API Services" tutorial (https://docs.coronalabs.com/tutorial/social/connectREST/index.html)
Replaced broken links in `network.*` and updated sample codes to reflect changes
Replaced branding with constants in `network.*`
> Small updates to network API and rebranding for REST tutorial

- bin/build.lua
- markdown/api/library/store/index.markdown
- resources/ats.html
Added link to Apple IAP plugin from Store API
Updated build version
Removed branding from ATS template
> Added link to Apple IAP, updated build version

- bin/aliases.lua
- markdown/api/library/display/loadRemoteImage.markdown
- markdown/guide/html5/plugins/index.markdown
Added alias for HTML5 - navigation bar was showing "Documentation  ▸  Developer Guides  ▸  [html5][guide.html5] "
Hopefully, this will fix it.
Replaced image links on `display.loadRemoteImage`
Replaced broken links for VK Direct Games plugin repository to GitHub - `HTML5 guide`
Replaced branding to constant - `HTML5 guide`
Replaced forum links and added link to Discord - `HTML5 guide`
Replaced branding with constant - `HTML5 guide`
> Updated links and rebranding

- markdown/api/library/sqlite3/index.markdown
luasqlite.luaforge.net/lsqlite3.html seems to have moved to lua.sqlite.org/index.cgi/doc/tip/doc/lsqlite3.wiki so replacing links.
Also replaced an old Corona reference with Solar2D.
> Replaced broken LuaSQLite Documentation link

- markdown/guide/start/installMac/index.markdown
- markdown/guide/start/installWin/index.markdown
> Adding JDK no longer required warning to install instructions

- markdown/guide/basics/configSettings/index.markdown
`print( display.pixelWidth / display.actualContentWidth )` only works when the app is in portrait orientation. If the app is in landscape orientation, then the `display.actualContentHeight` should be used instead.
> Fix an oversight with configSettings

- markdown/api/library/system/getInfo.markdown
The "build" property is already correctly explained under its corresponding heading at https://docs.coronalabs.com/api/library/system/getInfo.html#build. This is PR just removes the accidental duplicate text from under the bundleID heading.
> Remove duplicate text from incorrect location

- markdown/api/library/media/capturePhoto.markdown
When you set the destination, the event sent to the listener doesn't receive the image object.
> alert to developers about event

- bin/build.lua
- markdown/api/library/lfs/index.markdown
- markdown/guide/data/LFS/index.markdown
Old link to Kepler Project GitHub was dead. Looking at [this](https://github.com/lunarmodules/luafilesystem/commit/912e06714fc276c15b4d5d1b42bd2b11edb8deff) and some other Google searches, they seem to have moved to Lunar Modules. I updated the links to reflect that change. Still, I'd prefer a second opinion on this.
I also kept the old link in `build.lua` for archival purposes.
> Update LFS reference link, bump version number

- markdown/api/library/display/getDefault.markdown
- markdown/tutorial/media/extendAnchors/index.markdown
- markdown/tutorial/media/swapImages/index.markdown
Apply rebranding to Graphics/Audio/Animation pages at https://docs.coronalabs.com/tutorial/media/index.html
Remove unnecessary branding for display.setDefault()
> Rebranding for Tutorials -> Graphics/Audio/Animation

- markdown/api/library/system/getInfo.markdown
Referencing https://github.com/coronalabs/corona/pull/536
- Add links and description to new iOS accessibility features - `system.getInfo("reduceMotion"/"reduceTransparency"/"differentiateWithoutColor")`
- Add description for `"iosIdentifierForVendor"`
- Update Apple documentation link for `"iosIdentifierForVendor"`
> Add links and description for new accessibility features

- markdown/api/library/socket/index.markdown
"See also	LuaSocket Documentation" in [socket.*](https://docs.coronalabs.com/api/library/socket/index.html), was expected refer to LuaSocket reference.
> Fix LuaSocket broken link

- markdown/plugin/CoronaProvider_native_popup_social/index.markdown
Addressing issue #79 
Removed `iOS` from supported platforms list since iOS 8 is obsolete
> Add warning and link to Activity Popup plugin

- markdown/plugin/CoronaProvider_native_popup_activity/index.markdown
This is to link two plugins together so developers don't waste time searching.
- Add warning to use Social Popup for Android
- Add link to Social Popup(Android) from Activity Popup(iOS)
- Remove link to forums
> Add warning and link to Social Popup plugin

- markdown/guide/distribution/buildSettings/index.markdown
This change is to save developers' time.
> Move warning to a visible spot

- markdown/api/library/store/index.markdown
The link was intended to direct to Apple IAP plugin, but was instead directing to Amazon IAP.
Also updated the wording from "please see the new plugin" to "please use the new plugin".
> Fix incorrect internal link & update wording
