markdown/api/event/touch/index.markdown, markdown/api/event/touch/xDelta.markdown, markdown/api/event/touch/yDelta.markdown
These two features were added to Corona a long time ago, but apparently no documentation was ever added for them.
=> Add missing xDelta and yDelta to documentation

markdown/guide/distribution/androidResources/index.markdown
Fixed typos
Fixed "Adaptive Icons" external link
Cleared up "Using Android Studio" definition and linked official guide
=> Rebranding, fixed typos, added external links

markdown/index.markdown, resources/footer.html, resources/nav.markdown
Changed Corona to Solar2D on the main page and navigation
=> Rebranding top navigation bar, main page and changed footer information

markdown/api/indexHeader.markdown
Small change to expand documentation link click area
=> Expanded native docs link

bin/aliases.lua, bin/build.lua, markdown/guide/start/installWin/index.markdown
Added alias for Apple IAP plugin
Updated download links in build.lua
Added new constant for free plugins directory (will be used to replace Marketplace links)
Updated "Installing Solar2D - Windows" page
=> Updated constants, aliases and install page

markdown/guide/programming/index.markdown
Updated broken links
Removed broken links
Rebranding
=> Updated 'Getting Started' main page

bin/build.lua
Added new constant for Playground. This may be referenced later on 'Getting Started' pages or anywhere else.
Added comments to constants for later edits.
=> Added comments and a new constant

markdown/guide/programming/intro/index.markdown
Replaced broken links with working new ones
Added forums and Discord links
Updated social media links to Solar2D accounts
Removed Google+ and YouTube links
=> Rebranding, updated links and wording

markdown/api/library/timer/performWithDelay.markdown
Added link to timer library source code
Added gotcha description for timer.cancel()
Changed wording on pause and resume gotchas
=> Added link to source code, cancel gotcha

markdown/guide/programming/01/index.markdown
Added Wikipedia link to `API` definition
Changed package link to Solar2d-companion
Fixed formatting issues (hopefully)
Small changes
=> Changed link, fixed formatting, small changes

markdown/guide/programming/02/index.markdown
Added Wikipedia link to Game Design Document
Removed unnecessary branding
=> Added Wiki link, rebranding

markdown/api/library/timer/index.markdown
=> timer: Fixed link to cancelAll

markdown/api/type/BitmapPaint/scaleY.markdown
1) Added sentence in Gotchas about image-aspect ratio
2) Added sample-code to maintain image-aspect ratio
=> Added sample-code to maintain image aspect ratio

.gitignore, markdown/api/index.markdown, markdown/native/android/index.markdown, markdown/native/hostedPlugin.markdown, markdown/native/plugin/index.markdown
According to the solution provided to me by @Shchvova solving an issue with Android plugin, the documentation is extended with those tips.
=> Plugin Guide enhanced

bin/build.lua, markdown/guide/programming/03/index.markdown, resources/footer.html
Updated revision build number
Updated year in footer note to 2021
Rebranding
=> Rebranding, updated build number and year

markdown/api/type/GroupObject/index.markdown
=> Adding anchorChildren to properties

markdown/guide/events/detectEvents/index.markdown
=> Add a reference to windowState to the event guide

bin/build.lua, markdown/api/library/transition/index.markdown, markdown/api/library/transition/loop.markdown
Create page for transition.loop function
Add link from transition index page to .loop
Update Solar2D release version
Referencing #96  I'd like @depilz to take a look at this commit.
=> Create page for transition.loop

markdown/api/library/transition/loop.markdown
Fix for definition in #121 as pointed out by @depilz
=> Update function definition

markdown/tutorial/basics/ads/index.markdown, markdown/tutorial/basics/anonymousFunctions/index.markdown, markdown/tutorial/basics/codeFormatting/index.markdown, markdown/tutorial/basics/functionArguments/index.markdown, markdown/tutorial/basics/globals/index.markdown, markdown/tutorial/basics/scope/index.markdown
Rebranding for Tutorials/Basics pages
Update links that were broken, redirecting to other pages or no longer operational
Revise articles
=> Rebranding, update links, maintenance

markdown/guide/distribution/androidResources/index.markdown
Make changes to copying AndroidResources from SampleApp so it stands out
Change Solar2D strings to CORONA_CORE_PRODUCT variable
=> Make directive stand out, change brand to variable

markdown/guide/programming/04/index.markdown
https://docs.coronalabs.com/guide/programming/04/index.html
=> Rebranding for Getting Started Chapter 4

markdown/guide/programming/05/index.markdown, resources/footer.html
Rebranding for [Getting Started - Chapter 5](https://docs.coronalabs.com/guide/programming/05/index.html)
Update year information in footer. Updated this a bit earlier to 2023 but hey, we got 1 month left :)
=> Rebranding, update year info in footer

markdown/guide/programming/07/index.markdown
Change branding for [Chapter 7 — Sounds and Music](https://docs.coronalabs.com/guide/programming/07/index.html)
=> Change branding to constant variable for Chapter 7

markdown/guide/programming/06/index.markdown
Change branding for [Chapter 6 — Implementing High Scores](https://docs.coronalabs.com/guide/programming/06/index.html)
=> Change branding to constant variable for Chapter 6

markdown/guide/basics/debugging/index.markdown
Constant variable was not loading in the latest PR so I changed it to 'Solar2D' - not the solution I want 👎 
Changed Solar2D branding to CORONA_CORE_PRODUCT
=> Fix variable not loading, change branding

markdown/api/index.markdown, markdown/api/type/TextBox/index.markdown, markdown/api/type/TextField/getSelection.markdown, markdown/api/type/TextField/index.markdown, markdown/api/type/TextField/setSelection.markdown
getSelection documentation added
=> getSelection documentation added

markdown/plugin/pasteboard/index.markdown
=> Fix links for source code and sample

README.md, markdown/tutorial/basics/ads/index.markdown
Mostly grammar, I went through them mostly because I couldn't sleep yet and decided to do something constructive.
=> a few fixes

markdown/api/library/widget/newButton.markdown
=> Fixed typo

bin/build.lua, resources/footer.html
=> Update year and build information

markdown/plugin/unityads-v4/index.markdown
Updating links to Unity Ads pages for privacy and registration page
=> Update external links

markdown/plugin/admob/event/adsRequest/phase.markdown
Directly addressing the claim on the forums: https://forums.solar2d.com/t/solar2d-2025-3721-has-been-released/357403/16
=> Update "closed" phase definition

markdown/plugin/pasteboard/index.markdown
Addressing the issue #182 
_I've also submitted a PR to the sample project because it wasn't working properly. @Shchvova can you take a look at that as well? [Here](https://github.com/coronalabs/com.coronalabs-plugin.pasteboard/pull/3)_
=> Add Gotchas section to Pasteboard plugin
